test: socket-test: add missing include
test/socket-test/main.cc:76:9: error: ‘fd_set’ was not declared in this scope
test/socket-test/main.cc:79:27: error: ‘rdfs’ was not declared in this scope
...

Signed-off-by: Christian Eggers <ceggers@arri.de>