unit-test: Catch2: update to latest v2.x release
Catch2 < v2.13.5 does not work with glibc >= 2.34 as MINSIGSTKSZ and
SIGSTKSZ are not constant anymore on Linux:

https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html

test/unit-test/catch.hpp:9041:58: error: call to non-‘constexpr’
function ‘long int sysconf(int)’
 9041 |     constexpr static std::size_t sigStackSize = 32768 >=
MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;

This is been been addressed by Catch2 here:
https://github.com/catchorg/Catch2/blob/v2.x/docs/release-notes.md#2135

Include Catch2 via Git submodule as done for other dependencies.

Signed-off-by: Christian Eggers <ceggers@arri.de>